enter the number of process:5
process 1 is thinking
process 2 is thinking
process 3 is thinking
process 4 is thinking
process 5 is thinking
process 1 is eating
process 2 is thinking
process 3 is eating
process 4 is thinking
process 5 is thinking
process 5 is eating
process 1 is thinking
process 2 is eating
process 3 is thinking
process 4 is thinking
process 4 is eating
process 5 is thinking
process 1 is eating
process 2 is thinking
process 3 is thinking
process 3 is eating
process 4 is thinking
process 5 is eating
process 1 is thinking
process 2 is thinking
process 2 is eating
process 3 is thinking
process 4 is eating
process 5 is thinking
process 1 is thinking